name: MusicVideo

on:
  workflow_dispatch:
    inputs:
      concept:
        description: 'Music concept'
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: echo "Concept: ${{ github.event.inputs.concept }}"
