name: MV Generator

on:
  workflow_dispatch:
    inputs:
      input1:
        description: 'Test input'
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: echo "Input: ${{ github.event.inputs.input1 }}"
